### ISSUE TITLE
Implementar mejora clase User

### ISSUE THREAD

**Issue by xeivier** [JaviKx2/IWVG.SwC.FcoJavierReyes#2]
Descripción detallada de la mejora: [User - Feature#02 - Nombre en mayúsculas](https://github.com/JaviKx2/IWVG.SwC.FcoJavierReyes/wiki/2.-Features#feature02---nombre-en-may%C3%BAsculas)

Nota: No olvidar los test unitarios.

**Comment by betocols** [comment]
Creado el método nameToUpperCase() en la clase User con su respectivas pruebas.
