### ISSUE TITLE
Implementar mejora clase Point

### ISSUE THREAD

**Issue by xeivier** [JaviKx2/IWVG.SwC.FcoJavierReyes#3]
Descripción detallada de la mejora: [Point - Feature#01 - Habilitar la modificación de coordenadas](https://github.com/JaviKx2/IWVG.SwC.FcoJavierReyes/wiki/2.-Features#feature01---habilitar-la-modificaci%C3%B3n-de-coordenadas)

Nota: No olvidar los test unitarios.

**Comment by ccleon** [comment]
Método para modificar coordenadas hecho y testeado.
