### ISSUE TITLE
Implementar mejora clase Fraction (Feature#04 - Propia & Impropia)

### ISSUE THREAD

**Issue by xeivier** [JaviKx2/IWVG.SwC.FcoJavierReyes#4]
Descripción detallada de la mejora: [Fraction - Feature#04 - Propia & Impropia](https://github.com/JaviKx2/IWVG.SwC.FcoJavierReyes/wiki/2.-Features#feature04---propia--impropia)

Nota: No olvidar los test unitarios.

**Comment by xeivier** [comment]
Las fracciones impropias son las que tienen el numerador mayor o igual que el denominador. Necesario arreglar esto.

Nota: Modificar el test correspondiente también.

**Comment by tggarcia** [comment]
Método isImpropia arreglado

**Comment by xeivier** [comment]
Sigue siendo incorrecto. Ahora es igual que el método isPropia().
Revísalo de nuevo.

Adjunto foto:
![screenshot_2](https://cloud.githubusercontent.com/assets/18118080/18810425/9b8e6fa2-8295-11e6-8833-22ae6dc3c346.png)

**Comment by tggarcia** [comment]
No, fíjate que en la función isPropia devuelve true si el numerador es menor que el denominador y en isImpropia devuelve false si el numerador es menor que el denominador.

**Comment by xeivier** [comment]
No vi bien los return. Tienes razón. Cerrado queda. Saludos.
