### ISSUE TITLE
Implementar mejora clase Fraction (Feature#05 - Equivalentes)

### ISSUE THREAD

**Issue by xeivier** [JaviKx2/IWVG.SwC.FcoJavierReyes#5]
Descripción detallada de la mejora: [Fraction - Feature#05 - Equivalentes](https://github.com/JaviKx2/IWVG.SwC.FcoJavierReyes/wiki/2.-Features#feature05---equivalentes)

Nota: No olvidar los test unitarios.

**Comment by betocols** [comment]
Creado el método isEquivalent() en la clase Fraction con su respectiva prueba.
