### ISSUE TITLE
Implementar mejora clase Fraction (Feature#06 - Sumar, restar, multiplicar o dividir fracciones)

### ISSUE THREAD

**Issue by xeivier** [JaviKx2/IWVG.SwC.FcoJavierReyes#6]
Descripción detallada de la mejora: [Fraction - Feature#06 - Sumar, restar, multiplicar o dividir fracciones](https://github.com/JaviKx2/IWVG.SwC.FcoJavierReyes/wiki/2.-Features#feature06---sumar-restar-multiplicar-o-dividir-fracciones)

Nota: No olvidar los test unitarios.

**Comment by ccleon** [comment]
Metodos sumar, restar, multiplicar y dividir hechos y testeados.
